# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-resume' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Justin P. Barr
tagline: Management Constultant
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Manager at Alvarez & Marsal Corporate Performance Improvement in San Francisco. I specialize in business 
analytics, process improvement, data-driven decision making, and optimization modeling. My skill set includes 
Tableau, R, Python, SQL, Excel, and other data related technologies.'

#sidebar links
email: jbarr54@gmail.com
phone: (760) 519-4093
#website: blog.webjeda.com #do not add http://
linkedin: jpbarr
github: jpbarr
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
